name: Benchmarks

on:
  push:

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Install dependencies
        run: go mod download

      - name: Run benches
        run: make bench
