name: Tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race ./...
